# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:5.0
    container_name: up
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASS}
    ports:
      - "27017:27017"

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass ${ADMIN_PASS}
    ports:
      - "6379:6379"
